logging:
  level:
    org:
      springframework:
        security: TRACE
        oauth2: TRACE

server:
  port: 9090

spring:
  application:
    name: resource-server

  # URL to auhtorization server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/resource_server
    username: laurocorreia
    password: Vincere7
  jpa:
    show-sql: true

  # Email Configurations
  mail:
    host: smtp.mail.yahoo.com
    port: 587
    username: lauro.silveira@ymail.com
    password: klhpmqtinhjiosda
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
        connectiontimeout: 5000
        writetimeout: 3000