logging:
  level:
    org:
      springframework:
        security: TRACE
        oauth2: TRACE

server:
  port: 9090

spring:
  application:
    name: resource-server
    #call to auhtorization server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000